-- Sequência para Produto
CREATE SEQUENCE PRODUTO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Sequência para ProdutoImagem
CREATE SEQUENCE PRODUTO_IMAGEM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Tabela Produto
CREATE TABLE PRODUTO (
    ID            NUMBER(9) NOT NULL,
    DESCRICAO     VARCHAR2(250),
    PRECO_COMPRA  NUMBER(25, 16),
    PRECO_VENDA   NUMBER(25, 16),
    DATA_CADASTRO DATE
)

LOGGING;

-- Chave Primária na Tabela Produto
ALTER TABLE PRODUTO ADD CONSTRAINT PRODUTO_PK PRIMARY KEY ( ID );

-- Tabela ProdutoImagem
CREATE TABLE PRODUTO_IMAGEM (
    ID         NUMBER(9) NOT NULL,
    PRODUTO_ID NUMBER(9) NOT NULL,
    PRINCIPAL  NUMBER(1),
    URI_IMAGEM VARCHAR2(300)
)

LOGGING;

-- Chave Primária na Tabela ProdutoImagem
ALTER TABLE PRODUTO_IMAGEM ADD CONSTRAINT PRODUTO_IMAGEM_PK PRIMARY KEY ( ID,
                                                                          PRODUTO_ID );

-- Chave Estrangeira na Tabela ProdutoImagem
ALTER TABLE PRODUTO_IMAGEM
    ADD CONSTRAINT PRODUTO_FK FOREIGN KEY ( PRODUTO_ID )
        REFERENCES PRODUTO ( ID )
    NOT DEFERRABLE;